info:
 build:
  name: '%PROJECT_NAME%'
  description:
  version: '@version@'

springfox:
 title: ${info.build.name}
 description: ${info.build.description}
 version: ${info.build.version}

server:
  port: ${PORT:8080}